services:
  mongo:
    image: mongo:7
    container_name: nexusflow-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api-gateway:
    build: ./api-gateway
    container_name: nexusflow-gateway
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      FRONTEND_URL: http://localhost:5173
      AUTH_SERVICE_URL: http://auth-service:3001
      BOARD_SERVICE_URL: http://board-service:3002
      TASK_SERVICE_URL: http://task-service:3003
      FILE_SERVICE_URL: http://file-service:3004
      REALTIME_SERVICE_URL: http://realtime-service:3005
      MESSAGE_SERVICE_URL: http://message-service:3006
      NOTIFICATION_SERVICE_URL: http://notification-service:3007
      WORKSPACE_SERVICE_URL: http://workspace-service:3008
      JWT_SECRET: nexusflow_super_secret_dev
    depends_on:
      - auth-service
      - board-service
      - task-service
      - file-service
      - realtime-service
      - message-service
      - notification-service
      - workspace-service

  auth-service:
    build: ./services/auth-service
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      MONGODB_URI: mongodb://mongo:27017/nexusflow
      JWT_SECRET: nexusflow_super_secret_dev
    depends_on:
      - mongo

  board-service:
    build: ./services/board-service
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      MONGODB_URI: mongodb://mongo:27017/nexusflow
    depends_on:
      - mongo

  task-service:
    build: ./services/task-service
    ports:
      - "3003:3003"
    environment:
      PORT: 3003
      MONGODB_URI: mongodb://mongo:27017/nexusflow
    depends_on:
      - mongo

  file-service:
    build: ./services/file-service
    ports:
      - "3004:3004"
    environment:
      PORT: 3004
      MONGODB_URI: mongodb://mongo:27017/nexusflow
    depends_on:
      - mongo

  realtime-service:
    build: ./services/realtime-service
    ports:
      - "3005:3005"
    environment:
      PORT: 3005
      FRONTEND_URL: http://localhost:5173

  message-service:
    build: ./services/message-service
    ports:
      - "3006:3006"
    environment:
      PORT: 3006
      MONGODB_URI: mongodb://mongo:27017/nexusflow
    depends_on:
      - mongo

  notification-service:
    build: ./services/notification-service
    ports:
      - "3007:3007"
    environment:
      PORT: 3007
      MONGODB_URI: mongodb://mongo:27017/nexusflow
    depends_on:
      - mongo

  workspace-service:
    build: ./services/workspace-service
    ports:
      - "3008:3008"
    environment:
      PORT: 3008
      MONGODB_URI: mongodb://mongo:27017/nexusflow
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: nexusflow-frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:3000
    depends_on:
      - api-gateway

volumes:
  mongo_data:
